# Generated by Django 3.2.8 on 2022-05-16 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FlightType', models.CharField(max_length=50)),
                ('Rate', models.FloatField()),
                ('Description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='RoomCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=50)),
                ('Rate', models.FloatField()),
                ('Description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_number', models.IntegerField()),
                ('Beds', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Description', models.TextField(max_length=2000)),
                ('Image', models.ImageField(upload_to='room_image')),
                ('Capacity', models.IntegerField()),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Booking.roomcat')),
            ],
        ),
        migrations.CreateModel(
            name='FlightType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('People', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Description', models.TextField(max_length=2000, null=True)),
                ('Image', models.ImageField(upload_to='images')),
                ('FlightNumber', models.IntegerField()),
                ('FlightCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Booking.flightcat')),
            ],
        ),
        migrations.CreateModel(
            name='FlightBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Check_in', models.DateTimeField()),
                ('Check_out', models.DateTimeField()),
                ('Flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.flighttype')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Check_in', models.DateTimeField()),
                ('Check_out', models.DateTimeField()),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.room')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
